### PR TITLE
Add support for mypy

### PR DESCRIPTION
**Pull request by patrick-5546**
- In response to #130 

Thanks @athackst for writing up How-to-Add.md, I followed it to add support for mypy. One thing that I had to do was build a custom docker container to install ament_mypy, as it wasn't in the humble-dev image.

### CODE REVIEW

**Comment by patrick-5546** [comment]
Sounds good, once you do that I can remove the custom image I created in this PR

**Comment by athackst** [comment]
Ok, all ament packages should be added to the dev image now

**Comment by patrick-5546** [comment]
Update the PR accordingly, should be good to go now!

**Comment by athackst** [comment]
Thanks for your contribution!

**Comment by athackst** [comment]
Released last night https://github.com/athackst/vscode-ament-task-provider/releases/tag/v0.2.3

**Pull request merged**
